### ISSUE TITLE
no service.sh file?

### ISSUE THREAD

**Issue by Franzferdinan51** [bttcprotocol/launch#3] opened 2021-12-23 21:40 UTC
okay so to start im on ubuntu 20.04 trying to setup the launch directory but it keeps saying that service.sh isnt a file which makes sense considering it isnt where its looking either 

i try and run the following commands from the node deployment in the docs

cp -rf launch/mainnet-v1/sentry/sentry ~/node 

cp launch/mainnet-v1/service.sh ~/node

the first one succeeds the second i received the following error 

bttc@bttc:~$ sudo cp /root/launch/mainnet-v1/service.sh ~/node
cp: cannot stat '/root/launch/mainnet-v1/service.sh': No such file or directory

even running as root same issue with or without root

how/where can i find this file or what not to fix this error?

**Comment by xq-lu** [comment] 2022-02-28 02:55
hi,[Franzferdinan51](https://github.com/Franzferdinan51)
we have already removed the service.sh file .since we do not recommend users to run the node as a system service

**Comment by vivian1912** [comment] 2023-07-13 04:02
Thanks for your contribution to BTTC, this issue will be closed as no update for a long time.

Please feel free to re-open it if the issue is not resolved, thanks.

**Closed by vivian1912** 2023-07-13 04:02 UTC
